### ISSUE TITLE
Use CSS filters on Wikipedia math images

### ISSUE THREAD

**Issue by austinhartzheim** [austinhartzheim/dark.txt#5]
Use CSS filters to handle when Wikipedia generates math as PNGs.

This should invert the color of the text to white:
```CSS
img {
    filter: invert(100);
}
```
